# Generated by Django 3.2.16 on 2022-12-28 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='disliked_by',
            field=models.ManyToManyField(
                blank=True,
                related_name='_question_question_disliked_by_+',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='liked_by',
            field=models.ManyToManyField(
                blank=True,
                related_name='_question_question_liked_by_+',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='viewed_by',
            field=models.ManyToManyField(
                blank=True,
                related_name='_question_question_viewed_by_+',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
